# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

#development:
#  adapter: postgresql
#  database: ppdb_dev
#  pool: 5
#  timeout: 5000
test:
  adapter: postgresql
  database: ppdb_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ppdb
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  pool: 5
  database: db/development.sqlite3
  timeout: 5000

#test:
#  <<: *default
#  database: db/test.sqlite3

#production:
#  <<: *default
#  database: db/production.sqlite3
